### ISSUE TITLE
Use an internal interrupt?

### ISSUE THREAD

**Issue by sclarke81** [XRobots/WiperMotorServo#4]
I have to confess I don't have any Arduinos (hence not raising pull requests) but I do enjoy all your videos. Would it be better to use use an internal interrupt rather than a loop and the timing using millis()? I feel like this would be neater and give the option of putting the Arduino to sleep to save power? This interrupt would obviously need to be set to a lower priority than the pulse timer.

**Comment by AJMansfield** [comment]
> This interrupt would obviously need to be set to a lower priority than the pulse timer.

Arduino don't have multiple interrupt priorities, instead this is handled is by making the interrupt "reentrant" by calling `sei()` at the beginning. That lets other interrupts interrupt the current interrupt, but that also includes _itself_, meaning you also have to add a mutex guard to prevent the code from running a second time while it's in the middle of an operation.

Running the main code from an interrupt also has the disadvantage that your scheduling is now much less flexible. Multiple tasks that each take only a tiny fraction of one interrupt can't easily be run together in the same interrupt period, and code that takes multiple interrupt periods to run now has to be broken up, making the control logic often much more difficult. What it really comes down to though is that when the system comes under load, you end up spending a lot of extra time waiting around for the interrupt to happen instead of doing work.

A much better solution if you need the ability to sleep between tasks is to just use an actual scheduler. It doesn't have to be complicated, something super-basic like this is perfectly adequate for most things you're likely to do on Arduino:

```C
#define TASK_COUNT 8
typedef struct pending_item {
    void (*callback)(struct pending_item *self)
    unsigned long micros;
} pending_item;
pending_item tasks[TASK_COUNT];
pending_item * get_next_task(unsigned long now) {
    // Searches the tasks array for the lowest difference from now (negative means we're late)
    // Uses a O(N) linear search because it's actually faster for small N.
    pending_item * next_item = &tasks[0];
    for (size_t i = 1; i < sizeof(tasks)/sizeof(tasks[0]); i++){ 
        pending_item * item = &tasks[i];
        if (item->callback == NULL) continue;
        if ((signed long)(now - item->micros) < (signed long)(now - next_item->micros)) {
            next_item = item;
        }
    }
    return next_item;
}
void idle(signed long micros) {
    if(micros > 0) delayMicros(micros); // you could implement a low power sleep here
}
void do_tasks() {
    unsigned long now = micros();
    pending_item * item = get_next_task(now);
    if (next_item->callback == NULL) {
        println("No more tasks!");
        exit(0);
    } else {
        // if there's still time remaining until the scheduled task, idle for the difference
        idle((signed long)(micros() - next_item->micros));
        next_item->callback(next_item);
    }
}
```

The `idle` function is where you'd put the code to go to sleep to save power.
Essentially, you'd be checking if the requested idle time is long enough to go to sleep and wake up without missing the deadline.

Examples of how this scheduler could be used:

```C
void run_again_in_2s(pending_item *self) {
    println("Run again in 2 seconds.");
    self->micros = micros() + 2000000;
}
void run_once_per_second(pending_item *self) {
    println("Run exactly once per second.");
    self->micros += 1000000;
}
void run_10_times_and_stop(pending_item *self) {
    println("Run 10 times then stop.");
    static int count = 0
    if (++count > 10) self->callback = NULL;
    self->micros = micros() + 250000;
}

int multicount = 0;
void count_down_then_up(pending_item *self); //need forward declaration
void count_up_then_down(pending_item *self) {
    printf("Counting up:   &d/5\n", count);
    if (++multicount > 5) self->callback = &count_down_then_up;
    self->micros = micros() + 25000;
}
void count_down_then_up(pending_item *self) {
    printf("Counting down: &d/5\n", count);
    if (--multicount < 0) self->callback = &count_up_then_down;
    self->micros = micros() + 25000;
}

void setup() {
    for (size_t i = 0; i < sizeof(tasks)/sizeof(TASK_COUNT); i++){
        tasks[i].micros = micros();
    }
    tasks[0].callback = &run_again_in_2ms;
    tasks[1].callback = &run_1000_times_per_second;
    tasks[2].callback = &run_10_times_and_stop;
    tasks[3].callback = &count_up_then_down;
}
void loop() {
    do_tasks();
}
```

There are slightly more advanced ways of coding a scheduler that do involve using the timer interrupts, which are needed for some applications. Essentially, instead of using an `idle` routine, the scheduler sets up a dispatcher that will call the task as the timer interrupt handler and set the timer to trigger its interrupt at the scheduled time. That's a bit more complicated though and there isn't a clean library way to do it &mdash; it requires directly accessing the timer registers and interrupt vector tables and is often difficult to port even to other Arduinos.

**Comment by sclarke81** [comment]
Wow, thanks. That's a really thorough and informative answer. Thanks for taking the time to reply.
